
import java.util.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mfitr
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }
    //Initialise your process classes here!
    //START
    NfaProcess nfaProcess = new NfaProcess();
    RegularGrammar rgGen = new RegularGrammar();
        
    //END

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        introTextPane = new javax.swing.JTextPane();
        partOnePanel = new javax.swing.JPanel();
        partOneTitleLabel = new javax.swing.JLabel();
        nfaConvertButton = new javax.swing.JButton();
        stringInputField1 = new javax.swing.JTextField();
        stringInputField2 = new javax.swing.JTextField();
        stringInputField3 = new javax.swing.JTextField();
        stringInputField4 = new javax.swing.JTextField();
        checkStringButton = new javax.swing.JButton();
        clearStringButton = new javax.swing.JButton();
        stringLabel1 = new javax.swing.JLabel();
        stringLabel2 = new javax.swing.JLabel();
        stringLabel3 = new javax.swing.JLabel();
        stringLabel4 = new javax.swing.JLabel();
        nfaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        alphaText1 = new javax.swing.JTextField();
        alphaText2 = new javax.swing.JTextField();
        alphaText3 = new javax.swing.JTextField();
        alphaText4 = new javax.swing.JTextField();
        varText1 = new javax.swing.JTextField();
        varText2 = new javax.swing.JTextField();
        varText3 = new javax.swing.JTextField();
        varText4 = new javax.swing.JTextField();
        varText5 = new javax.swing.JTextField();
        varText6 = new javax.swing.JTextField();
        varText7 = new javax.swing.JTextField();
        varText8 = new javax.swing.JTextField();
        startText = new javax.swing.JTextField();
        finalText1 = new javax.swing.JTextField();
        finalText2 = new javax.swing.JTextField();
        finalText3 = new javax.swing.JTextField();
        finalText4 = new javax.swing.JTextField();
        finalText5 = new javax.swing.JTextField();
        finalText6 = new javax.swing.JTextField();
        finalText7 = new javax.swing.JTextField();
        finalText8 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        nfaTransitTable = new javax.swing.JTable();
        confirmNfaDefButton = new javax.swing.JButton();
        confirmNfaSetButton = new javax.swing.JButton();
        rgPanel = new javax.swing.JPanel();
        rgLabel = new javax.swing.JLabel();
        resetNfaButton = new javax.swing.JButton();
        partTwoTabbedPanel = new javax.swing.JTabbedPane();
        phaseOnePanel = new javax.swing.JPanel();
        phaseOneDeskPane = new javax.swing.JDesktopPane();
        phaseTwoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIS2151 Assignment");
        setMaximumSize(new java.awt.Dimension(900, 720));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 720));

        mainTabbedPane.setName(""); // NOI18N
        mainTabbedPane.setPreferredSize(new java.awt.Dimension(900, 729));

        homePanel.setPreferredSize(new java.awt.Dimension(900, 720));

        introTextPane.setEditable(false);
        introTextPane.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        introTextPane.setText("TIS2151 Theory of Computation\n\nAssignment (20%)\n\nTrimester 1 2019/2020\n\nLecturer: Dr. Nbhan D Salih\n\nTutorial Group: TT03\n\nGroup Members: -\n\n1- Muhammad Fitri Bin Amalludin - 1161300958\n2- Lim Zi Jie - 1161100143\n3- Ang Chong Wei - 1161304060\n4- Tebihi, Hicham - 1141326937");
        introTextPane.setOpaque(false);
        jScrollPane1.setViewportView(introTextPane);

        homePanel.add(jScrollPane1);

        mainTabbedPane.addTab("Home Tab", homePanel);

        partOnePanel.setPreferredSize(new java.awt.Dimension(900, 720));

        partOneTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        partOneTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        partOneTitleLabel.setText("Part 1 - NFA and Conversion of NFA to Regular Grammar");

        nfaConvertButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nfaConvertButton.setText("Convert to RG");
        nfaConvertButton.setEnabled(false);
        nfaConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfaConvertButtonActionPerformed(evt);
            }
        });

        stringInputField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        stringInputField1.setPreferredSize(new java.awt.Dimension(200, 30));
        stringInputField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringInputField1ActionPerformed(evt);
            }
        });

        stringInputField2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        stringInputField2.setPreferredSize(new java.awt.Dimension(200, 30));
        stringInputField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringInputField2ActionPerformed(evt);
            }
        });

        stringInputField3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        stringInputField3.setPreferredSize(new java.awt.Dimension(200, 30));
        stringInputField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringInputField3ActionPerformed(evt);
            }
        });

        stringInputField4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        stringInputField4.setPreferredSize(new java.awt.Dimension(200, 30));
        stringInputField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringInputField4ActionPerformed(evt);
            }
        });

        checkStringButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkStringButton.setText("Check String\n");
        checkStringButton.setEnabled(false);
        checkStringButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStringButtonActionPerformed(evt);
            }
        });

        clearStringButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearStringButton.setText("Clear");
        clearStringButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearStringButtonActionPerformed(evt);
            }
        });

        stringLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stringLabel1.setPreferredSize(new java.awt.Dimension(100, 30));

        stringLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stringLabel2.setPreferredSize(new java.awt.Dimension(100, 30));

        stringLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stringLabel3.setPreferredSize(new java.awt.Dimension(100, 30));

        stringLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stringLabel4.setPreferredSize(new java.awt.Dimension(100, 30));

        nfaPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Alphabets");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Variables");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Start");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Final(s)");

        alphaText1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alphaText1.setText("0");
        alphaText1.setMaximumSize(new java.awt.Dimension(50, 30));
        alphaText1.setMinimumSize(new java.awt.Dimension(50, 30));
        alphaText1.setPreferredSize(new java.awt.Dimension(30, 30));

        alphaText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alphaText2.setText("1");
        alphaText2.setMaximumSize(new java.awt.Dimension(50, 30));
        alphaText2.setMinimumSize(new java.awt.Dimension(50, 30));
        alphaText2.setPreferredSize(new java.awt.Dimension(30, 30));

        alphaText3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alphaText3.setMaximumSize(new java.awt.Dimension(50, 30));
        alphaText3.setMinimumSize(new java.awt.Dimension(50, 30));
        alphaText3.setPreferredSize(new java.awt.Dimension(30, 30));

        alphaText4.setEditable(false);
        alphaText4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alphaText4.setText("e");
        alphaText4.setMaximumSize(new java.awt.Dimension(50, 30));
        alphaText4.setMinimumSize(new java.awt.Dimension(50, 30));
        alphaText4.setPreferredSize(new java.awt.Dimension(30, 30));

        varText1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varText1.setText("A");
        varText1.setMaximumSize(new java.awt.Dimension(50, 30));
        varText1.setMinimumSize(new java.awt.Dimension(50, 30));
        varText1.setPreferredSize(new java.awt.Dimension(30, 30));

        varText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varText2.setText("B");
        varText2.setMaximumSize(new java.awt.Dimension(50, 30));
        varText2.setMinimumSize(new java.awt.Dimension(50, 30));
        varText2.setPreferredSize(new java.awt.Dimension(30, 30));

        varText3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varText3.setText("C");
        varText3.setMaximumSize(new java.awt.Dimension(50, 30));
        varText3.setMinimumSize(new java.awt.Dimension(50, 30));
        varText3.setPreferredSize(new java.awt.Dimension(30, 30));

        varText4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varText4.setMaximumSize(new java.awt.Dimension(50, 30));
        varText4.setMinimumSize(new java.awt.Dimension(50, 30));
        varText4.setPreferredSize(new java.awt.Dimension(30, 30));

        varText5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varText5.setMaximumSize(new java.awt.Dimension(50, 30));
        varText5.setMinimumSize(new java.awt.Dimension(50, 30));
        varText5.setPreferredSize(new java.awt.Dimension(30, 30));

        varText6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varText6.setMaximumSize(new java.awt.Dimension(50, 30));
        varText6.setMinimumSize(new java.awt.Dimension(50, 30));
        varText6.setPreferredSize(new java.awt.Dimension(30, 30));

        varText7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varText7.setMaximumSize(new java.awt.Dimension(50, 30));
        varText7.setMinimumSize(new java.awt.Dimension(50, 30));
        varText7.setPreferredSize(new java.awt.Dimension(30, 30));

        varText8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varText8.setMaximumSize(new java.awt.Dimension(50, 30));
        varText8.setMinimumSize(new java.awt.Dimension(50, 30));
        varText8.setPreferredSize(new java.awt.Dimension(30, 30));

        startText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startText.setText("A");
        startText.setMaximumSize(new java.awt.Dimension(50, 30));
        startText.setMinimumSize(new java.awt.Dimension(50, 30));
        startText.setPreferredSize(new java.awt.Dimension(30, 30));

        finalText1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalText1.setText("C");
        finalText1.setMaximumSize(new java.awt.Dimension(50, 30));
        finalText1.setMinimumSize(new java.awt.Dimension(50, 30));
        finalText1.setPreferredSize(new java.awt.Dimension(30, 30));

        finalText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalText2.setMaximumSize(new java.awt.Dimension(50, 30));
        finalText2.setMinimumSize(new java.awt.Dimension(50, 30));
        finalText2.setPreferredSize(new java.awt.Dimension(30, 30));

        finalText3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalText3.setMaximumSize(new java.awt.Dimension(50, 30));
        finalText3.setMinimumSize(new java.awt.Dimension(50, 30));
        finalText3.setPreferredSize(new java.awt.Dimension(30, 30));

        finalText4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalText4.setMaximumSize(new java.awt.Dimension(50, 30));
        finalText4.setMinimumSize(new java.awt.Dimension(50, 30));
        finalText4.setPreferredSize(new java.awt.Dimension(30, 30));

        finalText5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalText5.setMaximumSize(new java.awt.Dimension(50, 30));
        finalText5.setMinimumSize(new java.awt.Dimension(50, 30));
        finalText5.setPreferredSize(new java.awt.Dimension(30, 30));

        finalText6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalText6.setMaximumSize(new java.awt.Dimension(50, 30));
        finalText6.setMinimumSize(new java.awt.Dimension(50, 30));
        finalText6.setPreferredSize(new java.awt.Dimension(30, 30));

        finalText7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalText7.setMaximumSize(new java.awt.Dimension(50, 30));
        finalText7.setMinimumSize(new java.awt.Dimension(50, 30));
        finalText7.setPreferredSize(new java.awt.Dimension(30, 30));

        finalText8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalText8.setMaximumSize(new java.awt.Dimension(50, 30));
        finalText8.setMinimumSize(new java.awt.Dimension(50, 30));
        finalText8.setPreferredSize(new java.awt.Dimension(30, 30));

        nfaTransitTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nfaTransitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "alpha 1", "alpha 2", "alpha 3", "e"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nfaTransitTable.setEnabled(false);
        jScrollPane2.setViewportView(nfaTransitTable);

        confirmNfaDefButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmNfaDefButton.setText("Confirm NFA Definition");
        confirmNfaDefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNfaDefButtonActionPerformed(evt);
            }
        });

        confirmNfaSetButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmNfaSetButton.setText("Confirm NFA Transition");
        confirmNfaSetButton.setEnabled(false);
        confirmNfaSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNfaSetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nfaPanelLayout = new javax.swing.GroupLayout(nfaPanel);
        nfaPanel.setLayout(nfaPanelLayout);
        nfaPanelLayout.setHorizontalGroup(
            nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nfaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(nfaPanelLayout.createSequentialGroup()
                        .addGroup(nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nfaPanelLayout.createSequentialGroup()
                                .addComponent(finalText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalText7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalText8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nfaPanelLayout.createSequentialGroup()
                                .addComponent(alphaText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alphaText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alphaText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alphaText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nfaPanelLayout.createSequentialGroup()
                                .addComponent(varText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varText7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varText8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(startText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(nfaPanelLayout.createSequentialGroup()
                        .addComponent(confirmNfaDefButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmNfaSetButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        nfaPanelLayout.setVerticalGroup(
            nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nfaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nfaPanelLayout.createSequentialGroup()
                        .addGroup(nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(alphaText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alphaText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alphaText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alphaText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(varText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varText7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varText8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(startText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(finalText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalText7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalText8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(nfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmNfaDefButton)
                            .addComponent(confirmNfaSetButton))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        rgPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rgLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rgLabel.setText("No Regular Grammar generated yet");
        rgLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout rgPanelLayout = new javax.swing.GroupLayout(rgPanel);
        rgPanel.setLayout(rgPanelLayout);
        rgPanelLayout.setHorizontalGroup(
            rgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rgPanelLayout.setVerticalGroup(
            rgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        resetNfaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resetNfaButton.setText("Reset NFA");
        resetNfaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetNfaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout partOnePanelLayout = new javax.swing.GroupLayout(partOnePanel);
        partOnePanel.setLayout(partOnePanelLayout);
        partOnePanelLayout.setHorizontalGroup(
            partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partOnePanelLayout.createSequentialGroup()
                .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nfaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(partOnePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partOneTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(partOnePanelLayout.createSequentialGroup()
                                .addComponent(stringInputField4, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stringLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetNfaButton))
                            .addGroup(partOnePanelLayout.createSequentialGroup()
                                .addComponent(stringInputField1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stringLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkStringButton))
                            .addGroup(partOnePanelLayout.createSequentialGroup()
                                .addComponent(stringInputField2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stringLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearStringButton))
                            .addGroup(partOnePanelLayout.createSequentialGroup()
                                .addComponent(stringInputField3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stringLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(nfaConvertButton)))))
                .addContainerGap())
        );
        partOnePanelLayout.setVerticalGroup(
            partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partOnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(partOnePanelLayout.createSequentialGroup()
                        .addComponent(partOneTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nfaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stringInputField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkStringButton))
                            .addComponent(stringLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stringInputField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearStringButton)))
                    .addComponent(stringLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stringInputField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nfaConvertButton))
                    .addComponent(stringLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(stringInputField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stringLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resetNfaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(544, 544, 544))
        );

        mainTabbedPane.addTab("Part 1 (NFA to RG)", partOnePanel);

        partTwoTabbedPanel.setName(""); // NOI18N
        partTwoTabbedPanel.setPreferredSize(new java.awt.Dimension(745, 720));

        phaseOnePanel.setPreferredSize(new java.awt.Dimension(740, 720));

        phaseOneDeskPane.setPreferredSize(new java.awt.Dimension(720, 500));

        javax.swing.GroupLayout phaseOneDeskPaneLayout = new javax.swing.GroupLayout(phaseOneDeskPane);
        phaseOneDeskPane.setLayout(phaseOneDeskPaneLayout);
        phaseOneDeskPaneLayout.setHorizontalGroup(
            phaseOneDeskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        phaseOneDeskPaneLayout.setVerticalGroup(
            phaseOneDeskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout phaseOnePanelLayout = new javax.swing.GroupLayout(phaseOnePanel);
        phaseOnePanel.setLayout(phaseOnePanelLayout);
        phaseOnePanelLayout.setHorizontalGroup(
            phaseOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phaseOnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phaseOneDeskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        phaseOnePanelLayout.setVerticalGroup(
            phaseOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phaseOnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phaseOneDeskPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(616, Short.MAX_VALUE))
        );

        partTwoTabbedPanel.addTab("Phase One (CFG to CNF)", phaseOnePanel);

        javax.swing.GroupLayout phaseTwoPanelLayout = new javax.swing.GroupLayout(phaseTwoPanel);
        phaseTwoPanel.setLayout(phaseTwoPanelLayout);
        phaseTwoPanelLayout.setHorizontalGroup(
            phaseTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        phaseTwoPanelLayout.setVerticalGroup(
            phaseTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1127, Short.MAX_VALUE)
        );

        partTwoTabbedPanel.addTab("Phase Two (CNF to CYK)", phaseTwoPanel);

        mainTabbedPane.addTab("Part 2 (CFG to CNF to CYK)", partTwoTabbedPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void stringInputField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringInputField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringInputField3ActionPerformed

    private void stringInputField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringInputField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringInputField4ActionPerformed

    private void nfaConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfaConvertButtonActionPerformed
        for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
            rgGen.addState(nfaProcess.getState(i));
        }
        
        String rgStr = "";
        
        //rgGen.convertToRG();
        
        ArrayList<Nfa> nfaList = nfaProcess.getStateList();
        ArrayList<Integer> alphaList = nfaProcess.alphabetList;
        
        try{
            int step = 1;
            for (Nfa nfaTemp : nfaList) {
                if (nfaTemp.start_state == true) {
                    rgStr = nfaTemp.state_name + " -> "; //first part of the grammar line
                    for (int key : alphaList){ //secord part of the grammar line
                        rgStr = rgStr + String.valueOf(key);
                        rgStr = rgStr + nfaTemp.get_transition(key).state_name;
                        rgStr = rgStr + " | ";
                    }
                
                    if (nfaTemp.final_state == true) {
                        rgStr = rgStr + "e";
                    }
                    
                    ;
                }
                
                if (nfaTemp.start_state == false) {
                    rgStr = nfaTemp.state_name + " -> "; //first part of the grammar line
                    for (int key : alphaList){ //secord part of the grammar line
                        rgStr = rgStr + String.valueOf(key);
                        rgStr = rgStr + nfaTemp.get_transition(key).state_name;
                        rgStr = rgStr + " | ";
                    }
                
                    if (nfaTemp.final_state == true) {
                        rgStr = rgStr + "e";
                    }
                }
                
                System.out.println("Step " + step + ": " + rgStr);
                
                step++;
            }
        }
        catch(Exception e){
            System.out.println("NFA to G conversion failed!");
        }
        
        //rgLabel.setText(rgGen.getRG_String());
        System.out.println(rgStr);
        rgLabel.setText(rgStr);
    }//GEN-LAST:event_nfaConvertButtonActionPerformed

    private void stringInputField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringInputField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringInputField2ActionPerformed

    private void stringInputField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringInputField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringInputField1ActionPerformed

    private void checkStringButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStringButtonActionPerformed
        try{
            if (nfaProcess.checkString(stringInputField1.getText()) == true) {
                stringLabel1.setText("Accepted");
            }
            else{
                stringLabel1.setText("Rejected");
            }
            if (nfaProcess.checkString(stringInputField2.getText()) == true) {
                stringLabel2.setText("Accepted");
            }
            else{
                stringLabel2.setText("Rejected");
            }
            if (nfaProcess.checkString(stringInputField3.getText()) == true) {
                stringLabel3.setText("Accepted");
            }
            else{
                stringLabel3.setText("Rejected");
            }
            if (nfaProcess.checkString(stringInputField4.getText()) == true) {
                stringLabel4.setText("Accepted");
            }
            else{
                stringLabel4.setText("Rejected");
            }
        }
        catch(Exception e){
            System.out.println("Exception found from checkStringButtonActionPerformed");
        }
    }//GEN-LAST:event_checkStringButtonActionPerformed

    private void clearStringButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearStringButtonActionPerformed
        stringInputField1.setText("");
        stringInputField2.setText("");
        stringInputField3.setText("");
        stringInputField4.setText("");
    }//GEN-LAST:event_clearStringButtonActionPerformed

    private void confirmNfaDefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNfaDefButtonActionPerformed
        try{
            //for NFA alphabets
            nfaProcess.clearAlphabets(); //Clear memory of alphabets
            if (!alphaText1.getText().isBlank()) {
                nfaProcess.setAlphabet(Integer.parseInt(alphaText1.getText()));
                //rgGen.addAlpha(Integer.getInteger(alphaText1.getText()));
                nfaTransitTable.setValueAt(alphaText1.getText(), 0, 1);
            }
            if (!alphaText2.getText().isBlank()) {
                nfaProcess.setAlphabet(Integer.parseInt(alphaText2.getText()));
                //rgGen.addAlpha(Integer.getInteger(alphaText2.getText()));
                nfaTransitTable.setValueAt(alphaText2.getText(), 0, 2);
            }
            if (!alphaText3.getText().isBlank()) {
                nfaProcess.setAlphabet(Integer.parseInt(alphaText3.getText()));
                //rgGen.addAlpha(Integer.getInteger(alphaText3.getText()));
                nfaTransitTable.setValueAt(alphaText3.getText(), 0, 3);
            }
            //nfaProcess.setAlphabet(alphaText3.getText());
            //nfaProcess.setAlphabet(alphaText4.getText(), 3);
            //nfaTransitTable.setValueAt(alphaText1.getText(), 0, 1);
            //nfaTransitTable.setValueAt(alphaText2.getText(), 0, 2);
            //nfaTransitTable.setValueAt(alphaText3.getText(), 0, 3);
            //nfaTransitTable.setValueAt(alphaText4.getText(), 0, 4);

            //for NFA variables
            nfaProcess.clearStates(); //Clear memory of variables
            if (!varText1.getText().equals("")) {
                nfaProcess.addState(new Nfa(varText1.getText(), false, false));
                nfaTransitTable.setValueAt(varText1.getText(), 1, 0);
            }
            if (!varText2.getText().equals("")) {
                nfaProcess.addState(new Nfa(varText2.getText(), false, false));
                nfaTransitTable.setValueAt(varText2.getText(), 2, 0);
            }
            if (!varText3.getText().equals("")) {
                nfaProcess.addState(new Nfa(varText3.getText(), false, false));
                nfaTransitTable.setValueAt(varText3.getText(), 3, 0);
            }
            if (!varText4.getText().equals("")) {
                nfaProcess.addState(new Nfa(varText4.getText(), false, false));
                nfaTransitTable.setValueAt(varText4.getText(), 4, 0);
            }
            if (!varText5.getText().equals("")) {
                nfaProcess.addState(new Nfa(varText5.getText(), false, false));
                nfaTransitTable.setValueAt(varText5.getText(), 5, 0);
            }
            if (!varText6.getText().equals("")) {
                nfaProcess.addState(new Nfa(varText6.getText(), false, false));
                nfaTransitTable.setValueAt(varText6.getText(), 6, 0);
            }
            if (!varText7.getText().equals("")) {
                nfaProcess.addState(new Nfa(varText7.getText(), false, false));
                nfaTransitTable.setValueAt(varText7.getText(), 7, 0);
            }
            if (!varText8.getText().equals("")) {
                nfaProcess.addState(new Nfa(varText8.getText(), false, false));
                nfaTransitTable.setValueAt(varText8.getText(), 8, 0);
            }

            //for NFA start state
            if (!startText.getText().equals("")) {
                for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                    if (startText.getText().equals(nfaProcess.getStateList().get(i).get_statename())) {
                        nfaProcess.setStart(startText.getText());
                        nfaTransitTable.setValueAt(nfaProcess.getState(i).get_statename() + "^", ++i, 0);
                    }
                }
            } else {
                nfaProcess.getStateList().get(0).start_state = true; //Set the first variable as start state
            }

            //for NFA final state
            nfaProcess.resetAllFinal(); //Reset all states to non-final
            if (!finalText1.getText().equals("")) {
                for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                    if (finalText1.getText().equals(nfaProcess.getStateList().get(i).get_statename())) {
                        nfaProcess.setFinal(finalText1.getText());
                        nfaTransitTable.setValueAt(nfaProcess.getState(i).get_statename() + "*", ++i, 0);
                    }
                }
            }
            if (!finalText2.getText().equals("")) {
                for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                    if (finalText2.getText().equals(nfaProcess.getStateList().get(i).get_statename())) {
                        nfaProcess.setFinal(finalText2.getText());
                        nfaTransitTable.setValueAt(nfaProcess.getState(i).get_statename() + "*", ++i, 0);
                    }
                }
            }
            if (!finalText3.getText().equals("")) {
                for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                    if (finalText3.getText().equals(nfaProcess.getStateList().get(i).get_statename())) {
                        nfaProcess.setFinal(finalText3.getText());
                        nfaTransitTable.setValueAt(nfaProcess.getState(i).get_statename() + "*", ++i, 0);
                    }
                }
            }
            if (!finalText4.getText().equals("")) {
                for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                    if (finalText4.getText().equals(nfaProcess.getStateList().get(i).get_statename())) {
                        nfaProcess.setFinal(finalText4.getText());
                        nfaTransitTable.setValueAt(nfaProcess.getState(i).get_statename() + "*", ++i, 0);
                    }
                }
            }
            if (!finalText5.getText().equals("")) {
                for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                    if (finalText5.getText().equals(nfaProcess.getStateList().get(i).get_statename())) {
                        nfaProcess.setFinal(finalText5.getText());
                        nfaTransitTable.setValueAt(nfaProcess.getState(i).get_statename() + "*", ++i, 0);
                    }
                }
            }
            if (!finalText6.getText().equals("")) {
                for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                    if (finalText6.getText().equals(nfaProcess.getStateList().get(i).get_statename())) {
                        nfaProcess.setFinal(finalText6.getText());
                        nfaTransitTable.setValueAt(nfaProcess.getState(i).get_statename() + "*", ++i, 0);
                    }
                }
            }
            if (!finalText7.getText().equals("")) {
                for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                    if (finalText7.getText().equals(nfaProcess.getStateList().get(i).get_statename())) {
                        nfaProcess.setFinal(finalText7.getText());
                        nfaTransitTable.setValueAt(nfaProcess.getState(i).get_statename() + "*", ++i, 0);
                    }
                }
            }
            if (!finalText8.getText().equals("")) {
                for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                    if (finalText8.getText().equals(nfaProcess.getStateList().get(i).get_statename())) {
                        nfaProcess.setFinal(finalText8.getText());
                        nfaTransitTable.setValueAt(nfaProcess.getState(i).get_statename() + "*", ++i, 0);
                    }
                }
            }
        }
        catch(NullPointerException npe){
            System.out.println("NullPointerException found in confirmNfaDefButton");
        }
        
        nfaTransitTable.setEnabled(true);
        confirmNfaSetButton.setEnabled(true);
    }//GEN-LAST:event_confirmNfaDefButtonActionPerformed

    private void confirmNfaSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNfaSetButtonActionPerformed
        //Nfa initial_state = new Nfa();
        Nfa next_state = new Nfa();
        int transit_alpha;
        
        try{
            for (int y = 1; y <= nfaProcess.alphabetList.size(); y++) {
                for (int x = 1; x <= nfaProcess.getStateList().size(); x++) {
                    if (nfaTransitTable.getValueAt(x, y).toString() != "" || nfaTransitTable.getValueAt(x, y) != null) {
                        System.out.println("Cell : x=" + x + ", y= " + y);
                        transit_alpha = Character.getNumericValue(nfaTransitTable.getValueAt(0, y).toString().charAt(0));
                        next_state = (nfaProcess.getState(nfaTransitTable.getValueAt(x, y).toString()));
                        //Set totransition for the current state
                        nfaProcess.getStateList().get(x-1).set_totransition(transit_alpha, next_state);
                        System.out.println("Transition done!");
                        
                    }
                }
            }
            
            for (int i = 0; i < nfaProcess.getStateList().size(); i++) {
                rgGen.addState(nfaProcess.getState(i));
            }
        }
        catch(NullPointerException e){
            System.out.println("NullPointerException from confirmNfaSetButton");
        }
        
        checkStringButton.setEnabled(true);
        nfaConvertButton.setEnabled(true);
    }//GEN-LAST:event_confirmNfaSetButtonActionPerformed

    private void resetNfaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetNfaButtonActionPerformed
        nfaProcess.clearAlphabets();
        nfaProcess.clearStates();
        
        alphaText1.setText("");
        alphaText2.setText("");
        alphaText3.setText("");
        
        varText1.setText("");
        varText2.setText("");
        varText3.setText("");
        varText4.setText("");
        varText5.setText("");
        varText6.setText("");
        varText7.setText("");
        varText8.setText("");
        
        startText.setText("");
        
        finalText1.setText("");
        finalText2.setText("");
        finalText3.setText("");
        finalText4.setText("");
        finalText5.setText("");
        finalText6.setText("");
        finalText7.setText("");
        finalText8.setText("");
        
    }//GEN-LAST:event_resetNfaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
        
        try{
            View view = new View();
            Model model = new Model();
            Control control = new Control(view,model);
            //view.setVisible(true);
            
            //JInternalFrame phaseOneFrame = new JInternalFrame();
            JPanel phaseOneIntPanel = new JPanel();
            phaseOneIntPanel.add(view);
            //phaseOneDeskPane
        }
        catch(Exception e){
            System.out.println("Exception catched, unable to display Part 2 Phase One");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alphaText1;
    private javax.swing.JTextField alphaText2;
    private javax.swing.JTextField alphaText3;
    private javax.swing.JTextField alphaText4;
    private javax.swing.JButton checkStringButton;
    private javax.swing.JButton clearStringButton;
    private javax.swing.JButton confirmNfaDefButton;
    private javax.swing.JButton confirmNfaSetButton;
    private javax.swing.JTextField finalText1;
    private javax.swing.JTextField finalText2;
    private javax.swing.JTextField finalText3;
    private javax.swing.JTextField finalText4;
    private javax.swing.JTextField finalText5;
    private javax.swing.JTextField finalText6;
    private javax.swing.JTextField finalText7;
    private javax.swing.JTextField finalText8;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTextPane introTextPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton nfaConvertButton;
    private javax.swing.JPanel nfaPanel;
    private javax.swing.JTable nfaTransitTable;
    private javax.swing.JPanel partOnePanel;
    private javax.swing.JLabel partOneTitleLabel;
    private javax.swing.JTabbedPane partTwoTabbedPanel;
    private javax.swing.JDesktopPane phaseOneDeskPane;
    private javax.swing.JPanel phaseOnePanel;
    private javax.swing.JPanel phaseTwoPanel;
    private javax.swing.JButton resetNfaButton;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JPanel rgPanel;
    private javax.swing.JTextField startText;
    private javax.swing.JTextField stringInputField1;
    private javax.swing.JTextField stringInputField2;
    private javax.swing.JTextField stringInputField3;
    private javax.swing.JTextField stringInputField4;
    private javax.swing.JLabel stringLabel1;
    private javax.swing.JLabel stringLabel2;
    private javax.swing.JLabel stringLabel3;
    private javax.swing.JLabel stringLabel4;
    private javax.swing.JTextField varText1;
    private javax.swing.JTextField varText2;
    private javax.swing.JTextField varText3;
    private javax.swing.JTextField varText4;
    private javax.swing.JTextField varText5;
    private javax.swing.JTextField varText6;
    private javax.swing.JTextField varText7;
    private javax.swing.JTextField varText8;
    // End of variables declaration//GEN-END:variables
}
