/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mfitr
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        partOnePanel = new javax.swing.JPanel();
        partTwoTabbedPanel = new javax.swing.JTabbedPane();
        phaseOnePanel = new javax.swing.JPanel();
        phaseTwoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIS2151 Assignment");
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 750));
        setSize(new java.awt.Dimension(900, 750));

        mainTabbedPane.setName(""); // NOI18N

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Home Tab", homePanel);

        javax.swing.GroupLayout partOnePanelLayout = new javax.swing.GroupLayout(partOnePanel);
        partOnePanel.setLayout(partOnePanelLayout);
        partOnePanelLayout.setHorizontalGroup(
            partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        partOnePanelLayout.setVerticalGroup(
            partOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Part 1 (NFA to RG)", partOnePanel);

        partTwoTabbedPanel.setName(""); // NOI18N

        javax.swing.GroupLayout phaseOnePanelLayout = new javax.swing.GroupLayout(phaseOnePanel);
        phaseOnePanel.setLayout(phaseOnePanelLayout);
        phaseOnePanelLayout.setHorizontalGroup(
            phaseOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        phaseOnePanelLayout.setVerticalGroup(
            phaseOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        partTwoTabbedPanel.addTab("Phase One (CFG to CNF)", phaseOnePanel);

        javax.swing.GroupLayout phaseTwoPanelLayout = new javax.swing.GroupLayout(phaseTwoPanel);
        phaseTwoPanel.setLayout(phaseTwoPanelLayout);
        phaseTwoPanelLayout.setHorizontalGroup(
            phaseTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        phaseTwoPanelLayout.setVerticalGroup(
            phaseTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        partTwoTabbedPanel.addTab("Phase Two (CNF to CYK)", phaseTwoPanel);

        mainTabbedPane.addTab("Part 2 (CFG to CNF to CYK)", partTwoTabbedPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel homePanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel partOnePanel;
    private javax.swing.JTabbedPane partTwoTabbedPanel;
    private javax.swing.JPanel phaseOnePanel;
    private javax.swing.JPanel phaseTwoPanel;
    // End of variables declaration//GEN-END:variables
}
